# - Find REDISIMAGEHELPER library
# Once done this will define
#
#  REDISIMAGEHELPER_FOUND - This defines if we found hiredis
#  REDISIMAGEHELPER_INCLUDE_DIR - hiredis include directory
#  REDISIMAGEHELPER_LIBS - hiredis libraries
#  REDISIMAGEHELPER_DEFINITIONS - Compiler switches required for hiredis

SET(REDISIMAGEHELPER_DEFINITIONS ${PC_REDISIMAGEHELPER_CFLAGS_OTHER})

FIND_PATH(
    REDISIMAGEHELPER_INCLUDE_DIR
    NAMES "RedisImageHelper.hpp"
    PATH_SUFFIXES "redisimagehelper"
)

FIND_LIBRARY(REDISIMAGEHELPER_LIBS NAMES redisimagehelper
   HINTS
   ${PC_REDISIMAGEHELPER_LIBDIR}
   ${PC_REDISIMAGEHELPER_LIBRARY_DIRS}
)

INCLUDE(FindPackageHandleStandardArgs)
FIND_PACKAGE_HANDLE_STANDARD_ARGS(redisimagehelper DEFAULT_MSG REDISIMAGEHELPER_LIBS REDISIMAGEHELPER_INCLUDE_DIR)
